### ISSUE TITLE
panic: open /osm/geofabrik.yml: no such file or directory

### ISSUE THREAD

**Issue by ImreSamu** [julien-noblet/download-geofabrik#30]
version:  2.2.0
panic, when calling from another directory - where no `geofabrik.yml`

expected:  a simple warning, without a panic
not critical 

```
root@b7c773354067:/osm# /tools/download-geofabrik list
2018/03/25 18:13:42 open /osm/geofabrik.yml: no such file or directory
panic: open /osm/geofabrik.yml: no such file or directory

goroutine 1 [running]:
log.Panic(0xc420055e00, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:326 +0xc0
main.catch(0x857ac0, 0xc4201826f0)
        /home/travis/gopath/src/github.com/julien-noblet/download-geofabrik/download-geofabrik.go:107 +0xae
main.main()
        /home/travis/gopath/src/github.com/julien-noblet/download-geofabrik/download-geofabrik.go:123 +0x10d2
root@b7c773354067:/osm#
root@b7c773354067:/osm# /tools/download-geofabrik --version
2.2.0
```
it is ok, when `.geofabrik.yml` exist
```
root@b7c773354067:/osm# cd /tools
root@b7c773354067:/tools# ./download-geofabrik download monaco
2018/03/25 18:17:52 monaco.osm.pbf downloaded.
2018/03/25 18:17:53 monaco.osm.pbf.md5 downloaded.
2018/03/25 18:17:53 Checksum OK for monaco.osm.pbf
```

**Comment by julien-noblet** [comment]
This is due to error handling...

I need to use ```recover()``` for beter errors handling.

**Comment by ImreSamu** [comment]
similar panic - when I made a typo
( version: 2.2.1 )

```
root@9a502c05e7ad:/tools# ./download-geofabrik download africka -k
2018/03/25 19:59:20 africka is not in config
 Please use "list" command
panic: africka is not in config
 Please use "list" command

goroutine 1 [running]:
log.Panic(0xc420057e00, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:326 +0xc0
main.catch(0x8575e0, 0xc420368590)
        /home/travis/gopath/src/github.com/julien-noblet/download-geofabrik/download-geofabrik.go:107 +0xae
main.main()
        /home/travis/gopath/src/github.com/julien-noblet/download-geofabrik/download-geofabrik.go:155 +0x8be
root@9a502c05e7ad:/tools#
```

**Comment by julien-noblet** [comment]
I've just made a Quick&dirty fix...
I think some error must reach Panic.
But I'm agree with you for not really fatal troubles, Panic is too aggressive... ^^

I'm working to have a better error handling ASAP.

**Comment by julien-noblet** [comment]
It will be better with this fix :smile: Use Fatalln() is better.
